language: java
jdk: oraclejdk8
install: true
script: mvn clean install
cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
deploy:
  provider: releases
  api_key:
    secure: KGfzaU5morfV1cMTYc02r42cdWeiWxDlRbvQdj8ZQFHqwrKN1HaHkazlYvd4Kf2nWdGqeRVeuins1/+UqPm9v/HX2bVSbFLO26YGZLqmBWp3PRVRhSyUDbmotILcoSF3DBijKxr7/d1j3yh2ZaJY6OytOl64DGhX/yJ+5ADBIRflDM065jfGmSU+nDXaPbd1Cacf7S9eHIa//KqmachdZjZP50vwfJ5+ObTjMTXnAkz1kfJ+66Bs8C7Yiu6dz0EVooujEVAIL3Whf6mIULiQtETOvtLrgFBiXz/n0G0kzMTe5VJ7S9kXIxlCioUEHljlO8WOx51UcbrRYvn21ayYDk6gytXzGzG3wgONt+DUl8OFP4ZMkQVf+D+15Z8KUdRlO4R/mMM0bchKmZYdiVqE48BbTeu3/S/21mbIqxpEpl9L4iEtNJo/PeZZ3sHonur21pvsQfv8x+BXkCUoUrjF+6nhePS8zAiUp59IggsXY4hDJxcQUqwVpIQfa72Mrilr1rlgpJnsIJf6I4KU74R81tkMaSHpilKKdw4mSnidXrSdEbvOK1hKm23xIpLZuuxFhNR8+P/Qke2Fe3yxyjcdLZJeWsCFXgwXdtT8PN4qeQFjlnKKBZs5Z6XU6geom3E2rsBSHkQu3xLYEl5mBYvnK8XyZbB9ZAJ2hbasPTXJ9qI=
  file:
  - ota2-repository-service/target/ota2-repository-service.war
  - ota2-indexing-service/target/ota2-indexing-service.zip
  skip_cleanup: true
  on:
    repo: OpenTravel/OTM-DE-Compiler
    tags: true
