language: java
jdk: openjdk8
install: true
script: mvn clean install -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
cache:
  directories:
  - "$HOME/.m2"
after_success:
- bash <(curl -s https://copilot.blackducksoftware.com/ci/travis/scripts/upload)
deploy:
  provider: releases
  api_key:
    secure: fEhAXz+QiTHA4anZ/PTwTjXRNGMnTQ/o90tiDvOEWSvM4hCNJR6KH688NBIaZ2ugi8gSBFSIgSHd7p1uIs9IWrEN2c2FRNWfFt3xOVJXr8bm/IvbsWZpH3OCBh9ozW6AiZb6R5cym6VoUfDeDIEv5x6nLzBWkR8Pr9RHpuThCd+pY8xTj2kDAydAmMEvi7D7wWZklCqE61A4SuQvXgEVvMcRfOHnAWB1Kmfks/4qicrd4CRRsWZhuGK17GnPUawtfEhtDj2e87gNp9qd+oyI0nEOZ+RsklUCRafz/bUCu8f8Z0fNqQZ+zv4ZHuEyQW7FgOdWj2+MK1pqVB7UboK/8U+OmWnTGaA6CcVgQSC0aRRsj0yi4nNflmFKRFvmKUnRhxLXI9YJ9jwuvg9RPzYB+HcVKmRBoWirgrzrTdsc8qA0qY418QGMrOLCYsrZTNXJeL/glU5N6RzD8f2KpQBjfjkyHhzYIOZAa0NujYJYQ6zVo8fER6LDqGmKC6I9BrBk7mBXx6GpPtkuti7lBRxeB8HVD7/f+O+udX+EQ1EC3vN3CT8U/7i2KpbUQuQYyISp5Gt2I5rLFuptgtVZQZC4OfkhGJwBLTk+enCsBmPU7lRd7rpr/7xMDFXcrIrjWH6U/CXUpWw8KVw8X8oiTush1K2nImIwZBX9CKIlr+luj/8=
  file:
  - ota2-repository-service/target/ota2-repository-service.war
  - ota2-indexing-service/target/ota2-indexing-service.zip
  skip_cleanup: true
  on:
    repo: OpenTravel/OTM-DE-Compiler
    tags: true
    