---
- name: --> Configure Apache Web Server Proxy for OTM Repository
  hosts: all
  vars_files:
    - vars/default-vars.yml
    - "{{inventory_dir}}/vars/{{inventory_hostname}}-vars.yml"
    - vars/otm-repository-vars.yml
  tasks:
  - name: Setup OS-specific configuration (Debian)
    set_fact:
      package_name: apache2
      conf_directory: /etc/apache2/conf-enabled
      modules_directory: /usr/lib/apache2/modules
    when: ansible_distribution == 'Debian'
  - name: Setup OS-specific configuration (Ubuntu)
    set_fact:
      package_name: apache2
      conf_directory: /etc/apache2/conf-enabled
      modules_directory: /lib/apache2/modules
    when: ansible_distribution == 'Ubuntu'
  - name: Setup OS-specific configuration (CentOS or RHEL)
    set_fact:
      package_name: httpd
      conf_directory: /etc/httpd/conf.d
      modules_directory: /etc/httpd/modules
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  - name: Install the apache2/httpd package
    package:
      name: "{{package_name}}"
      state: latest
  - name: Install the configuration file for the OTM repository proxy
    template:
      src: "templates/proxy-config/otm-proxy.j2"
      dest: "{{conf_directory}}/otm-proxy.conf"
  - name: Restart the apache2 service
    service:
      name: "{{package_name}}"
      state: restarted
    