---
- name: --> Startup OTM Repository Server
  hosts: all
  vars_files:
    - vars/default-vars.yml
    - "{{inventory_dir}}/vars/{{inventory_hostname}}-vars.yml"
    - vars/otm-repository-vars.yml
  tasks:
  - import_tasks: subtasks/start-indexing.yml
  - import_tasks: subtasks/start-tomcat.yml
