---
- name: --> Shutdown OTM Repository Tomcat Server
  block:
  - name: Shutdown Tomcat service process
    service:
      name: ota2-tomcat
      state: stopped
  - name: Wait for service shutdown to complete
    wait_for:
      port: "{{tomcat_port}}"
      state: stopped
      timeout: 60
      delay: 10
