---
- name: --> Shutdown OTM Repository Indexing Service
  block:
  - name: Shutdown ota2-indexing-service process
    service:
      name: ota2-indexing
      state: stopped
  - name: Wait for service shutdown to complete
    wait_for:
      port: "{{indexing_activemq_port}}"
      state: stopped
      timeout: 60
