---
- name: --> Start OTM Repository Indexing Service
  service:
    name: ota2-indexing
    state: started
- name: Wait for service startup to complete
  wait_for:
    port: "{{indexing_activemq_port}}"
    timeout: 10
